// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {  

  //@codescene(disable:"Complex Method")
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['webAPI']! ,
    appId: '1:575869883887:web:8f5065bafc46ecb65f921a',
    messagingSenderId: '575869883887',
    projectId: 'blog-d0fc7',
    authDomain: 'blog-d0fc7.firebaseapp.com',
    storageBucket: 'blog-d0fc7.firebasestorage.app',
    measurementId: 'G-QNN02N7NRS',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['andoirdAPI']!,
    appId: '1:575869883887:android:bb5a9947f0a668eb5f921a',
    messagingSenderId: '575869883887',
    projectId: 'blog-d0fc7',
    storageBucket: 'blog-d0fc7.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['mac_iosAPI']!,
    appId: '1:575869883887:ios:896859e33f231c6c5f921a',
    messagingSenderId: '575869883887',
    projectId: 'blog-d0fc7',
    storageBucket: 'blog-d0fc7.firebasestorage.app',
    iosBundleId: 'com.example.blog',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['mac_iosAPI']!,
    appId: '1:575869883887:ios:896859e33f231c6c5f921a',
    messagingSenderId: '575869883887',
    projectId: 'blog-d0fc7',
    storageBucket: 'blog-d0fc7.firebasestorage.app',
    iosBundleId: 'com.example.blog',
  );
}
