// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu3J9GSWeRYdEuIe22N7Wtjnwjh8rhnSQ',
    appId: '1:915085217042:web:14a5fd2a465c17854637cb',
    messagingSenderId: '915085217042',
    projectId: 'bloc-695c5',
    authDomain: 'bloc-695c5.firebaseapp.com',
    storageBucket: 'bloc-695c5.firebasestorage.app',
    measurementId: 'G-PFNNQWJGZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5lm6rd6rfSDPukowloi9D_TBYxlTE8Tw',
    appId: '1:915085217042:android:dca61a4284f006374637cb',
    messagingSenderId: '915085217042',
    projectId: 'bloc-695c5',
    storageBucket: 'bloc-695c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy8FAwgA45jK4LDqNs-KMt1goE1_5yviw',
    appId: '1:915085217042:ios:3a15c0bb2cecc71f4637cb',
    messagingSenderId: '915085217042',
    projectId: 'bloc-695c5',
    storageBucket: 'bloc-695c5.firebasestorage.app',
    iosBundleId: 'com.example.blog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy8FAwgA45jK4LDqNs-KMt1goE1_5yviw',
    appId: '1:915085217042:ios:3a15c0bb2cecc71f4637cb',
    messagingSenderId: '915085217042',
    projectId: 'bloc-695c5',
    storageBucket: 'bloc-695c5.firebasestorage.app',
    iosBundleId: 'com.example.blog',
  );
}
